baseURL = 'https://harut-harutyunyan.github.io'
languageCode = 'en-us'
title = 'My New Blog'

DefaultContentLanguage = "en"

theme = "beautifulhugo"
# pygmentsStyle = "trac"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  # useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true


[[Params.bigimg]]
 src = "img/sphere.jpg"
 desc = "Sphere"
 # position: see values of CSS background-position.
 position = "center top"


[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Harut Harutyunyan"
  website = ""
  email = "har8unyan@gmail.com"

  github = "username"
  linkedin = "username"
#   youtube = "user/username" # or channel/channelname
#   paypal = "username"
  telegram = "har8unyan"
  discord = "invite code (https://discord.gg/XXXXXXX)"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
