baseURL = 'https://harut-harutyunyan.github.io'
languageCode = 'en-us'
title = 'My New Blog'

DefaultContentLanguage = "en"

theme = "beautifulhugo"
# pygmentsStyle = "trac"
pygmentsCodeFences = true
pygmentsUseClasses = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Compositor's Thoughts" # Set a different text for the header on the home page
  subtitle = "Mostly technical info about digital compositing and not only."
  mainSections = ["post","posts"]
  logo = "img/jojack-icon.png" # Expecting square dimensions
  favicon = "img/webicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  # rss = true
  comments = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true


[[Params.bigimg]]
 src = "img/bigimg_0001.jpg"
 #  desc = "Sphere"
 #  position: see values of CSS background-position.
 position = "center top"


[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Harut Harutyunyan"
  website = ""
  email = "har8unyan@gmail.com"

  github = "username"
  linkedin = "username"
  telegram = "har8unyan"
  discord = "invite code (https://discord.gg/XXXXXXX)"
  artstation = "harutharutyunyan"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
